tutorialsIndex_en = {"I. How to play Greed?", "II. Kilika", "III. Mi'hen", "IV. Merchants"}

tutorialsInfo_en = {
    {
        {name = "01. Introduction", text = "Greed Online is an online MMORPG based on Tibia version 8.6. It is built with The Forgotten Server 1.5, a virtual server capable of emulating the game and keeping it open online for players from all over the world, and OTClient 2.0b (mehah), capable of integrating automatic bot, animations, graphics, etc. directly from the client.", img = "imgs/basic/b1"}, 
		{name = "02. Experience", text = "Your goal in the game is to level up by accumulating experience so that your character is stronger and stronger. Experience is gained by attacking and killing creatures you can find while exploring the continent.\n\nThere are two main cities that you will need to explore: Kilika and Mi'hen. On your journey through these cities you will encounter difficult challenges that will lead you to incredible rewards.", img = "imgs/basic/b2"}, 
        {name = "03. Control Types", text = "We recommend having the 'Classic Control' box activated in the options/control panel. If this box is not checked, you must include the 'Ctrl' key in your actions. Holding down the 'Ctrl' key and right-clicking on a creature or object will open its context menu.\n\nWith 'Classic Control' actions such as attacking, opening creature bodies, using sewers, opening your backpack, etc., are carried out performed automatically without opening the context menu when you right-click with the cursor on your target.\n\nIt is advisable to maximize your 'Hotkey delay' so that typing on your keyboard is faster.", img = "imgs/basic/b3"}, 
        {name = "04. Movement", text = "To walk use the arrow keys on your keyboard. Another option is to lock your number pad (to the right of the keyboard) so you can use the numbers to move around. The numbers 1, 3, 7 and 9 will move your character diagonally.", img = "imgs/basic/b4"}, 	
        {name = "05. Combat", text = "The 'Health Information' menu shows the amount of health and mana of your character. Your character passively regenerates health and mana. You can regenerate life with healing magic and healing potions. You can also regenerate mana with mana potions.\n\nAlso the 'Capacity' indicates how much weight (o.z) the character can carry. The 'Soul' indicates the limit of runes that the character can make and is recharged by killing creatures or training.\n\nThe 'Combat Controls' panel shows the fighting modes of your character, you can choose between 'aggressive', 'balanced ' and 'defensive'.\n\nThe 'Battle' panel allows you to select a target and attack it by pressing the left click. You can also open the context menu of the target by pressing 'Ctrl' and right clicking.", img = "imgs/basic/b5"}, 
        {name = "06. Skills", text = "The 'skills' panel displays all of your character's stats. The 'experience' bar will fill up as you kill creatures. If you reach the maximum your character will level up. 'Stamina' is the maximum amount of time you can hunt without rest.\n\nYour 'skills' are divided into 'magic level', 'fist fighting', 'maul fighting', 'sword fighting', ' ranged combat', 'shield' and 'fishing'. To increase the level of your skills you must use magic, attack creatures, take or block physical damage, train in the temple portal, or use a fishing rod.", img = "imgs/basic/b6"},
        {name = "07. Inventory", text = "Your character's inventory contains the items that your character can carry until your 'capacity' is exhausted. It consists of 10 main slots.\n\nThe 'armor', 'legs', 'boots', 'ring', 'amulet', and 'shield' slots allow you to equip defensive items to your character.\n\nThe 'weapon' slot allows you to equip a one-handed or two-handed weapon. If your weapon is two-handed, your shield slot must be free. The 'equipment' slot allows you to equip crossbow and bow ammo or light-emitting items, backpacks, ropes, etc.\n\nThe 'container' slot is for equipping a backpack or bag and filling it with items, gold, creature products, equipment, etc.\n\nTo put an item in your backpack, hover over the item, press left click and drag the item into your container. You can open your backpack with right click if you use 'Tibia Classic Control' or use 'Ctrl' and right click to open the 'context menu' of your backpack.", img = "imgs/basic/b7"}, 
        {name = "08. Outfits", text = "To change your clothes hold down the 'Ctrl' key and click on your character with the right mouse button then select 'Set Outfit'.\n\nIf you want to unlock new outfits you must complete quests, or use 'greed points'. The clothes are only aesthetic and do not grant any type of additional characteristic in the character's attributes.", img = "imgs/basic/b8"}, 	
        {name = "09. Hotkeys", text = "'Hotkeys' allow you to quickly assign actions on your keyboard via the 'hotkey panel' or the 'action bar' located at the top of the chat.\n\nThe 'add' button allows you to add a new 'key' to 'hotkey panel'. The 'edit text' slot allows you to assign a text. If you choose to enable 'send automatically' the sending of the text to the chat will be immediate.\n\nYou should know that if you write 'magic words' in the 'edit text' box and activate 'send automatically' these words will be conjured instantly by pressing the 'key' they were assigned to.\n\nYou can also assign 'keys' to the use of 'items' and choose between the following actions: 'use it on your character', 'use it on the target' or ' use with crosshair'.", img = "imgs/basic/b9"}, 		
 },
    {
        {name = "01. Kilika Temple", text = "The 'temple' is the place where you first appear in the game. This area is protected and no character or creature can emit or receive attacks. If your character dies, he will reappear in the temple but will lose a percentage of experience, and the items you have in your inventory.\n\nTo prevent the loss of items you can use a necklace called 'amulet of loss'. You can also prevent experience loss if your character gets 'blessings'.", img = "imgs/inter/a1"},
        {name = "02. Kilika Deposit", text = "To get to the deposit you must walk west from Kilika's temple.\n\nThe 'deposit' is where the characters store their items. Each player has their own 'deposit' and no other character can access it. This area contains a bank NPC where you can deposit or withdraw your money. You can also find several merchant NPCs to whom you can sell valuable items or buy important supplies.", img = "imgs/inter/a2"},
        {name = "03. Kilika Port", text = "To get to the port you must walk northwest from Kilika's deposit.\n\nAt Kilika's 'port' you can travel for 20 gold coin to the city of Mi'hen. Be careful when traveling using ships as they are not protected areas.", img = "imgs/inter/a3"},
    },	
    {
        {name = "01. Mi'hen Temple", text = "The 'temple' is the place where you first appear in the game. This area is protected and no character or creature can emit or receive attacks. If your character dies, he will reappear in the temple but will lose a percentage of experience, and the items you have in your inventory.\n\nTo prevent the loss of items you can use a necklace called 'amulet of loss'. You can also prevent experience loss if your character gets 'blessings'.", img = "imgs/advanced/c1"},
        {name = "02. Mi'hen Deposit", text = "To get to the deposit you must walk south from the Mi'hen temple.\n\nThe 'deposit' is where the characters store their items. Each player has their own 'deposit' and no other character can access it. This area contains a bank NPC where you can deposit or withdraw your money. You can also find several merchant NPCs to whom you can sell valuable items or buy important supplies.", img = "imgs/advanced/c2"},
        {name = "03. Mi'hen Port", text = "To get to the port you have to walk southeast from the Mi'hen deposit.\n\nAt the Mi'hen 'port' you can travel for 20 gold coin to the town of Kilika. Be careful when traveling using ships as they are not protected areas.", img = "imgs/advanced/c3"},
    },	
    {
        {name = "01. Promotions", text = "Father Zuke and Isaaru are NPCs capable of changing your 'hometown' and creating 'marks' on your map. In addition, your character can buy a 'promotion' to improve your vocation for 20,000 gold coins.\n\nThat is, if your character is 'knight' it will become 'elite knight', 'paladin' to 'royal paladin', ' sorcerer' to 'master sorcerer', and druid to 'elite druid'. This will increase your character's health and mana per second regeneration values ​​and unlock new spells.", img = "imgs/profesion/p1"},
		{name = "02. Blessings", text = "Jassu and Nimrook are NPCs that sell 'blessings'. The value of blessings is calculated by a formula based on your character's level.\n\nAcquiring 'blessings' prevents your character from losing experience or inventory items upon death. Upon death, your blessings will disappear and you will need to repurchase them if you wish to regain this protection.\n\nJassu and Nimrook also sell the 'amulet of loss' item that prevents item loss when equipped for 10,000 gold if you use the 'trade' command.", img = "imgs/profesion/p2"},
		{name = "03. PVP Blessings", text = "Amanda and Alia sell the special blessing called 'twist of fate' or 'turn of fate'. This boon does not prevent you from losing your gear or reduce experience lost on death, however it does protect your normal boons if you die in PvP combat.", img = "imgs/profesion/p3"},
		{name = "04. Magic Objects", text = "It is essential for all vocations to use potions and magic items to go hunting. You can find Jyscal in Kilika and Mi'hen's deposit. You also have the option to offer a lottery ticket for your empty vials.", img = "imgs/profesion/p4"},
        {name = "05. Tools", text = "Equipment is paramount when exploring. In the NPC Keyakku you will find available tools such as shovels, ropes, backpacks, etc. In addition, it allows you to trade rings and amulets.", img = "imgs/profesion/p5"},
		{name = "06. Weapons and Munitions", text = "Rin is the classic weapons NPC that allows you to buy weapons for low levels, ranged weapons such as crossbows, bows, etc. and ammunition. You can also get money quickly by selling the weapons you don't use.", img = "imgs/profesion/p6"},
		{name = "07. Armors and Shields", text = "O'aka is the classic armor NPC that allows you to buy low level armor and shields to make your character stronger. You can also get money quickly by selling shields and armor that you don't use.", img = "imgs/profesion/p7"},
		{name = "08. Bank", text = "In the bank your character can deposit, withdraw or transfer money so as not to load it in coins. In addition, there is the option of selling valuable objects such as gems, sapphires, rubies, pearls, among others.", img = "imgs/profesion/p8"},
        {name = "09. Products", text = "Brother is the owner of the creature products shop, this shop is important to get money quickly, since most of the products that you will gather by killing creatures can be sold here.", img = "imgs/profesion/p9"},	
		{name = "10. Blacksmithing", text = "Blacksmithing is an ancient art that only Nhadala can perform to perfection. Certain metals, or tools, necessary to progress through Greed's quests can be crafted from this NPC.", img = "imgs/profesion/p10"},	
		{name = "11. Outfits", text = "Your character's clothing can be unlocked at Maroda, this NPC will offer you the option to unlock the first or second decoration of your clothing in exchange for specific items.", img = "imgs/profesion/p11"},
		{name = "12. Premium Points", text = "Seymour is able to exchange your premium points for greed currency. The greed currency is the currency that physically represents your donation points, the NPC allows you to change one, ten, or a hundred coins at a time.", img = "imgs/profesion/p12"},		
    },			
}