tutorialsIndex_es = {"I. ¿Como jugar Greed?", "II. Kilika", "III. Mi'hen", "IV. Comerciantes"}

tutorialsInfo_es = {
    {
        {name = "01. Introducion", text = "Greed Online es un juego MMORPG en línea basado en la versión de Tibia 8.6. Está construido con The Forgotten Server 1.5, un servidor virtual capaz de emular el juego y mantenerlo en línea de forma abierta para jugadores de todo el mundo, y OTClient 2.0b (mehah), capaz de integrar bot automatico, animaciones, graficas, etc. directamente desde el cliente.", img = "imgs/basic/b1"}, 
		{name = "02. Experiencia", text = "Tu objetivo en el juego subir de nivel acumulando experiencia para que tu personaje sea cada ves mas fuerte. La experiencia se obtiene al atacar y matar criaturas que puedes encontrar explorando el continente.\n\nExisten dos ciudades principales que deberas explorar: Kilika y Mi'hen. En tu viaje por estas ciudades encontraras dificiles desafios que te guiaran a increibles recompensas.", img = "imgs/basic/b2"}, 
        {name = "03. Tipos de controles", text = "Recomendamos tener la casilla 'Classic Control' activada en el panel de opciones/control. Si esta casilla no esta activada, debes incluir la tecla 'Ctrl' en tus acciones. Presionar la tecla 'Ctrl' y el click derecho sobre una criatura u objeto abrira su menu contextual.\n\nCon 'Classic Control' las acciones como atacar, abrir cuerpos de criaturas, usar alcantarillas, abrir tu mochila, etc., se llevan a cabo automaticamente sin abrir el menu contextual al presionar el click derecho con el cursor sobre tu objetivo.\n\nSe aconseja subir al maximo tu 'Hotkey delay' para que la digitacion en tu teclado sea mas rapida.", img = "imgs/basic/b3"}, 
        {name = "04. Movimiento", text = "Para caminar utiliza las flechas de tu teclado. Otra opcion es bloquear tu teclado numerico (a la derecha del teclado) y asi podras utilizar los numeros para moverte. Los numeros 1, 3, 7 y 9 moveran tu personaje de forma diagonal.", img = "imgs/basic/b4"}, 	
        {name = "05. Combate", text = "El menu de 'Health Information' muestra la cantidad de vida y mana de tu personaje. Tu personaje regenera vida y mana de forma pasiva. Puedes regenerar vida con magias de curacion y pociones de curacion. Tambien puedes regenerar mana con pociones de mana.\n\nAdemas la 'Capacidad' indica cuanto peso (o.z) puede cargar el personaje. El 'Soul' indica el limite de runas que puede hacer el personaje y se recarga matando criaturas o entrenando.\n\nEl panel 'Controles de Combate' muestra los modos de pelea de tu personaje, puedes escoger entre 'agresivo', 'balanceado' y 'defensivo'.\n\nEl panel 'Batalla' te permite seleccionar un objetivo y atacarlo presionando el click izquierdo. Ademas puedes abrir el menu contextual del objetivo presionando 'Ctrl' y click derecho.", img = "imgs/basic/b5"}, 
        {name = "06. Habilidades", text = "El panel de 'habildades' muestra todas las estadisticas de tu personaje. La barra de 'experiencia' se llenará en la medida que mates criaturas. Si llega al máximo tu personaje subira de nivel. La 'resistencia' es la cantidad maxima de tiempo que puedes cazar sin descanso.\n\nTus 'habilidades' se dividen en 'nivel magico', 'combate a puños', 'combate con mazo', 'combate con espada', 'combate a distancia', 'escudo' y 'pesca'. Para aumentar el nivel de tus habilidades debes utilizar magias, atacar criaturas, recibir o bloquear daño fisico, entrenar en el portal del templo, o utilizar una caña de pescar.", img = "imgs/basic/b6"},
        {name = "07. Inventario", text = "El inventario de tu personaje contiene los objetos que tu personaje puede llevar hasta agotar tu 'capacidad'. Se compone de 10 ranuras principales.\n\nLas ranuras de 'armadura', 'piernas', 'botas', 'anillo', 'amuleto', y 'escudo', te permiten equipar objetos defensivos para tu personaje.\n\nLa ranura de 'arma' te permite equipar un arma de una o dos manos. Si tu arma es de dos manos la ranura de tu escudo debe quedar libre. La ranura de 'equipamientos' te permite equipar municion de ballestas y arcos u objetos que emitan luz, mochilas, cuerdas, etc.\n\nLa ranura del 'contenedor' sirve para equipar una mochila o una bolsa y llenarla con objetos, oro, productos de criaturas, equipamiento, etc.\n\nPara llevar un objeto a tu mochila, situa el cursor sobre el objeto, presiona el click izquierdo y arrastra el objeto a tu contenedor. Puedes abrir tu mochila con el click derecho si usas 'Tibia Classic Control' o utilizar 'Ctrl' y click derecho para abrir el 'menu contextual' de tu mochila.", img = "imgs/basic/b7"}, 
        {name = "08. Vestimenta", text = "Para cambiar su ropa mantenga presionada la tecla 'Ctrl' y haga click en su personaje con el boton derecho del raton despues selecciones 'Fijar Outfit'.\n\nSi quieres desloquear nuevas vestimentas debes completar misiones, o utilizar 'puntos greed'. Las vestimentas son solo esteticas y no otorgan ningun tipo de caracteristica adicional en los atributos del personaje.", img = "imgs/basic/b8"}, 	
        {name = "09. Teclas rápidas", text = "Las 'teclas rápidas' te permiten asignar acciones de forma rapida en tu teclado por medio del 'panel de hotkeys' o la 'barra de accion' ubicada en la parte superior del chat.\n\nEl boton 'add' permite añadir una nueva 'tecla' al 'panel de hotkeys'. La ranura de 'editar texto' permite asignar un texto. Si optas por habilitar 'enviar automaticamente' el envio del texto al chat sera inmediato.\n\nDebes saber que si escribes 'palabras magicas' en la casilla de 'editar texto' y activas 'enviar automaticamente' estas palabras serán conjuradas de forma instantanea al presionar la 'tecla' a la que se asignaron.\n\nAdemas puedes asignar 'teclas' a la utilizacion de 'objetos' y elegir entre las siguientes acciones: 'usarlo en tu personaje', 'usarlo en el objetivo' o 'usar con punto de mira'.", img = "imgs/basic/b9"}, 		
 },
    {
        {name = "01. Templo de Kilika", text = "El 'templo' es el lugar donde apareces por primera ves en el juego. Esta area esta protegida y ningun personaje o criatura puede emitir o recibir ataques. Si tu personaje muere, volvera a aparecer en el templo pero perdera un porcentaje de experiencia, y los objetos que tengas en tu inventario.\n\nPara prevenir la perdida de objetos puedes utilizar un collar llamado 'amulet of loss'. Ademas puedes prevenir la perdida de experiencia si tu personaje obtiene 'blessings'.", img = "imgs/inter/a1"},
        {name = "02. Deposit de Kilika", text = "Para llegar al deposit debes caminar hacia el oeste desde el templo de Kilika.\n\nEl 'deposit' es donde los personajes guardan sus objetos. Cada jugador tiene su propio 'deposit' y ningun otro personaje puede acceder a el. Esta zona contiene un NPC de banco donde puedes depositar o retirar tu dinero. Ademas puedes encontrar varios NPCs comerciantes a los cuales puedes vender objetos valiosos o comprar insumos importantes.", img = "imgs/inter/a2"},
        {name = "03. Puerto de Kilika", text = "Para llegar al puerto debes caminar hacia el noroeste desde el deposit de Kilika.\n\nEn el 'puerto' de Kilika puedes viajar por 20 gold coin a la ciudad de Mi'hen. Ten cuidado al viajar utilizando barcos ya que no son zonas protegidas.", img = "imgs/inter/a3"},
    },	
    {
        {name = "01. Templo de Mi'hen", text = "El 'templo' es el lugar donde apareces por primera ves en el juego. Esta area esta protegida y ningun personaje o criatura puede emitir o recibir ataques. Si tu personaje muere, volvera a aparecer en el templo pero perdera un porcentaje de experiencia, y los objetos que tengas en tu inventario.\n\nPara prevenir la perdida de objetos puedes utilizar un collar llamado 'amulet of loss'. Ademas puedes prevenir la perdida de experiencia si tu personaje obtiene 'blessings'.", img = "imgs/advanced/c1"},
        {name = "02. Deposit de Mi'hen", text = "Para llegar al deposit debes caminar hacia el sur desde el templo de Mi'hen.\n\nEl 'deposit' es donde los personajes guardan sus objetos. Cada jugador tiene su propio 'deposit' y ningun otro personaje puede acceder a el. Esta zona contiene un NPC de banco donde puedes depositar o retirar tu dinero. Ademas puedes encontrar varios NPCs comerciantes a los cuales puedes vender objetos valiosos o comprar insumos importantes.", img = "imgs/advanced/c2"},
        {name = "03. Puerto de Mi'hen", text = "Para llegar al puerto debes caminar hacia el sureste desde el deposit de Mi'hen.\n\nEn el 'puerto' de Mi'hen puedes viajar por 20 gold coin a la ciudad de Kilika. Ten cuidado al viajar utilizando barcos ya que no son zonas protegidas.", img = "imgs/advanced/c3"},
    },	
    {
        {name = "01. Promociones", text = "Father Zuke e Isaaru son NPCs capaces de cambiar tu 'hometown' (ciudad natal) y crear 'mark' (marcas) en tu mapa. Ademas tu personaje puede comprar una 'promotion' para mejorar tu vocacion por 20.000 monedas de oro.\n\nEs decir, si tu personaje es 'knight' pasará a ser 'elite knight', 'paladin' a 'royal paladin', 'sorcerer' a 'master sorcerer', y druid a 'elite druid'. Esto incrementara los valores de regeneracion de vida y mana por segundo de tu personaje y desbloqueará nuevos hechizos.", img = "imgs/profesion/p1"},
		{name = "02. Bendiciones", text = "Jassu y Nimrook son NPCs que venden 'blessings'. El valor de las bendiciones es calculado por una formula basada en el nivel de tu personaje.\n\nAdquirir 'blessings' previene que tu personaje pierda experiencia u objetos de su inventario al morir. Al morir, tus blessings desapareceran y deberas volver a comprarlos si quieres volver a contar con esta protección.\n\nJassu y Nimrook tambien venden el objeto 'amulet of loss' que previene la perdida de objetos al ser equipado en 10.000 monedas de oro si usas el comando 'trade'.", img = "imgs/profesion/p2"},
		{name = "03. Bendición PVP", text = "Amanda y Alia venden la bendicion especial llamada 'twist of fate' o 'giro del destino'. Esta bendicion no evita que pierdas tu equipo o reduce la experiencia perdida al morir, sin embargo, protege tus bendiciones normales si mueres en un combate PvP.", img = "imgs/profesion/p3"},
		{name = "04. Objetos Magicos", text = "Es primordial para todas las vocaciones utilizar pociones y objetos magicos para ir de caceria. Puedes encontrar a Jyscal en el deposit de Kilika y Mi'hen. Ademas tiene la opcion de ofrecer un ticket de lotería por tus viales vacios.", img = "imgs/profesion/p4"},
        {name = "05. Equipamiento", text = "Los equipamientos son primordiales a la hora de explorar. En el NPC Keyakku encontraras disponible herramientas como palas, cuerdas, mochilas, etc. Ademas, te permite comerciar anillos y amuletos.", img = "imgs/profesion/p5"},
		{name = "06. Armas y Municiones", text = "Rin es el clasico NPC de armas que permite comprar armas para niveles bajos, armas a distancia como ballestas, arcos, etc. y municiones. Ademas puedes obtener dinero rapidamente vendiendo las armas que no utilices.", img = "imgs/profesion/p6"},
		{name = "07. Armadura y Escudos", text = "O'aka es el clasico NPC de armaduras que permite comprar armaduras y escudos de nivel bajo para hacer a tu personaje mas fuerte. Ademas puedes obtener dinero rapidamente vendiendo los escudos y armaduras que no utlices.", img = "imgs/profesion/p7"},
		{name = "08. Banco", text = "En el banco tu personaje puede depositar, retirar o transferir dinero para no cargarlo en monedas. Ademas, existe la opcion de vender objetos valuables como gemas, safiros, rubies, perlas, entre otros.", img = "imgs/profesion/p8"},
        {name = "09. Productos", text = "Brother es el dueño de la tienda de productos de criaturas, esta tienda es importante para obtener dinero rapidamente, ya que la mayor parte de los productos que reunirás al matar criaturas se podrán vender aquí.", img = "imgs/profesion/p9"},	
		{name = "10. Herrería", text = "La herrería es un arte antiguo que solo Nhadala puede ejecutar a la perfección. Ciertos metales, o herramientas, necesarias para avanzar en las misiones de Greed, pueden ser creadas en este NPC.", img = "imgs/profesion/p10"},	
		{name = "11. Vestimentas", text = "Las vestimentas de tu personaje pueden ser desbloqueadas en Maroda, este NPC te ofrecera la opcion de desbloquear el primer o segundo adorno de tu vestuario a cambio de objetos especificos.", img = "imgs/profesion/p11"},
		{name = "12. Puntos Premium", text = "Seymour es capaz de intercambiar tus puntos premium por greed currency. La greed currency es la moneda que representa fisicamente tus puntos de donacion, el NPC permite cambiar una, diez, o cien monedas a la ves.", img = "imgs/profesion/p12"},		
    },			
}